default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: resefer

development:
  <<: *default
  database: mountain_dev

test:
  <<: *default
  database: mountains_test

production:
  <<: *default
  database: mountains_prod
